name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Runs on pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> $GITHUB_ENV
      - name: Set Heroku API key
        run: echo "HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }}" >> $GITHUB_ENV

      - name: Deploy to Heroku
        run: |
          # Example deployment script (ensure Heroku CLI is installed)
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku login --api-key ${{ secrets.HEROKU_API_KEY }}
          git remote add heroku https://git.heroku.com/your-app-name.git
          git push heroku main
